$ErrorActionPreference = "Stop"

$workspaceRoot = Split-Path -Parent $PSScriptRoot
$venvPython = Join-Path $workspaceRoot ".venv\\Scripts\\python.exe"
$requirementsPath = Join-Path $workspaceRoot "requirements.txt"

if (-not (Test-Path $venvPython)) {
  throw "Virtual environment not found: $venvPython"
}

$freezeOutput = & $venvPython -m pip freeze
if ($LASTEXITCODE -ne 0) {
  throw "pip freeze failed"
}

$header = @(
  "# Auto-generated by scripts/freeze_requirements.ps1",
  "# Do not edit manually if you use scripts/pip_sync.ps1",
  ""
)

Set-Content -LiteralPath $requirementsPath -Value ($header + $freezeOutput) -Encoding utf8
Write-Host "requirements.txt updated."

